services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Persistent Redis data

  nextjs:
    build: ./kgquiz-dashboard
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./kgquiz-dashboard:/app
      - /app/node_modules             # Isolate host/node_modules
      - /app/.next                    # Isolate Next.js cache
    working_dir: /app

volumes:
  redis_data:  # Named volume for Redis persistence